### ISSUE TITLE
Dependencies not seen

### ISSUE THREAD

**Issue by rikvdkleij** [SublimeLinter/SublimeLinter-ghc#2]
SublimeLinter complaints:
Could not find module 'Test.Hspec'

while it's defined in cabal file.

What can be the problem? Do I miss something. Just building with cabal works.

**Comment by martinfinke** [comment]
If anyone is still interested: This can be solved (at least for what I need) by editing the User *SublimeLinter.sublime-settings* file.

Under the key `user.linters.ghc.args` there's should be an array. Add this line to it:

```json
"-package-db .cabal-sandbox/x86_64-osx-ghc-7.8.3-packages.conf.d"
```

Make sure you modify the `x86_64-osx-ghc-7.8.3` part with your arch, OS and `ghc` version, so the path actually points to the dir inside your *.cabal-sandbox*.

This seems to at least solve the problem of `ghc` not finding packages which are (only) installed in the sandbox.
